name: build-and-release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '1.0.0'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Blender Addon
        uses: BlenderKit/blender-addon-build@main
        with:
          name: 'OptFlowCam'
          build-command: ''
          build-location: './src/optFlowCam'
          do-checkout: 'true'
          exclude-files: '.git;.github;.gitignore'
  Release:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Release addon
        uses: BlenderKit/blender-addon-release@main
        with:
          artifact_name: OptFlowCam
          release_name: OptFlowCam
          version: ${{github.event.inputs.version}} 
